#!/usr/bin/env php
<?php
require __DIR__.'/bootstrap.php';
//var_dump($argv);
/***
 * ss-panel xcat script
 */
use App\Command\XCat;
$cat = new XCat();
switch($argv[1]){
    case("install"):
        return $cat->install();
    case("addadmin"):
        return $cat->addAdmin();
    default:
        return $cat->defaultAction();
}