<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUserTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('user', function (Blueprint $table) {
            $table->increments('id');
            $table->string('user_name', 128);
            $table->string('email', 32);
            $table->string('pass', 64);
            $table->string('passwd', 16);
            $table->integer('t')->default(0);
            $table->bigInteger('u')->default(0);
            $table->bigInteger('d')->default(0);
            $table->bigInteger('transfer_enable')->default(0);
            $table->integer('port')->default(0);
            $table->tinyInteger('switch')->default(1);
            $table->tinyInteger('enable')->default(1);
            $table->tinyInteger('type')->default(1);
            $table->integer('last_get_gift_time')->default(0);
            $table->integer('last_check_in_time')->default(0);
            $table->integer('last_rest_pass_time')->default(0);
            $table->timestamp('reg_date')->default('1989-06-04 03:10:29');
            $table->integer('invite_num')->default(0);
            $table->integer('is_admin')->default(0);
            $table->integer('ref_by')->default(0);
            $table->integer('expire_time')->default(0);
            $table->string('method', 64)->default('rc4-md5');
            $table->tinyInteger('custom_method')->default(0);
            $table->tinyInteger('custom_rss')->default(0);
            $table->string('protocol', 128)->default('origin');
            $table->string('protocol_param', 128)->default("");
            $table->string('obfs', 128)->default('plain');
            $table->string('obfs_param', 128)->default("");
            $table->tinyInteger('is_email_verify')->default(0);
            $table->string('reg_ip', 128)->default('127.0.0.1');

            $table->unique('email', 'email');
            $table->unique('port', 'port');

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('user');
    }
}
