<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateSsNodeTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('ss_node', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name', 128);
            $table->integer('type');
            $table->string('server', 128);
            $table->string('method', 64)->default('rc4-md5');
            $table->string('protocol', 128)->default('origin');
            $table->string('protocol_param', 128)->nullable();
            $table->string('obfs', 128)->default('plain');
            $table->string('obfs_param', 128)->nullable();
            $table->float('traffic_rate')->default(1);
            $table->string('info', 128);
            $table->string('status', 128);
            $table->integer('offset');
            $table->integer('sort');

            

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('ss_node');
    }
}
