<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateSsNodeInfoLogTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('ss_node_info_log', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('node_id');
            $table->float('uptime');
            $table->string('load', 32);
            $table->integer('log_time');

            $table->index('node_id', 'node_id');
            $table->index('log_time', 'log_time');

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('ss_node_info_log');
    }
}
