<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUserTrafficLogTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('user_traffic_log', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id');
            $table->integer('u');
            $table->integer('d');
            $table->integer('node_id');
            $table->float('rate');
            $table->string('traffic', 32);
            $table->integer('log_time');

            $table->index('user_id', 'user_id');
            $table->index('node_id', 'node_id');
            $table->index('log_time', 'log_time');
            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('user_traffic_log');
    }
}
