<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateSsChgCodeTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('ss_chg_code', function (Blueprint $table) {
            $table->integer('id');
            $table->string('code', 128);
            $table->integer('time');
            $table->bigInteger('traffic');
            $table->string('tag', 64);
            $table->integer('add_time');
            $table->integer('status');
            $table->integer('user_id');
            $table->integer('use_time');

            

            

        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('ss_chg_code');
    }
}
